apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-service
  template:
    metadata:
      labels:
        app: geo-service
    spec:
      containers:
        - name: geo
          image: geo-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_URL
              value: redis://redis:6379

---
apiVersion: v1
kind: Service
metadata:
  name: geo-service
spec:
  selector:
    app: geo-service
  ports:
    - port: 3001
      targetPort: 3001