apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-service
  template:
    metadata:
      labels:
        app: geo-service
    spec:
      containers:
        - name: geo-service
          image: geo-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: REDIS_TTL_SECONDS
              value: '300'
            - name: ROUTING_SERVICE_URL
              value: http://routing-service:3002
            - name: AUDIT_SERVICE_URL
              value: http://audit-service:3003
